repositories:
- name: traefik
  url: https://helm.traefik.io/traefik


releases:
- name: mytraefik
  chart: ./charts/mytraefik
  namespace: traefikns
  createNamespace: true
  values:
    - ./values/mytraefik.yaml

- name: application
  chart: ./charts/application
  namespace: app
  createNamespace: true
